language: php

env:
  global:
    - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"http://localhost:8080"},"PaulGibbs\\WordpressBehatExtension":{"path":"%paths.base%/tmp/wordress","wpcli":{"binary":"%paths.base%/vendor/bin/wp"}}}}'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: WORDPRESS_VERSION=nightly
    - php: 7.2
      env: WORDPRESS_VERSION=latest
    - php: 7.1
      env: WORDPRESS_VERSION=latest
    - php: 7.0
      env: WORDPRESS_VERSION=latest
    - php: 7.0
      env: WORDPRESS_VERSION=4.7.7
    - php: 7.0
      env: WORDPRESS_VERSION=4.6.8

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install
  # install and configure WordPress.
  - bin/setup-wp.sh
  # install and run Selenium.
  - bin/setup-selenium.sh
  # setup webserver.
  - bin/setup-server.sh

script:
  - vendor/bin/phpunit
  - vendor/bin/behat

after_script:
  # Tidy up after test run.
  # See https://github.com/travis-ci/travis-ci/issues/6861
  - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'java' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'Xvfb' | awk '{print $2}')