language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"$WORDPRESS_URL"},"PaulGibbs\\WordpressBehatExtension":{"path":"$WORDPRESS_DIR"}}}'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:

  # disable xDebug.
  - phpenv config-rm xdebug.ini || true

  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install

  # install and configure WordPress.
  - bin/setup-wp.sh
  # install and run Selenium.
  - bin/setup-selenium.sh
  # setup webserver.
  - bin/setup-server.sh

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
