language: php
php:
  - nightly
  - latest
  - '7.2'
  - '7.1'
  - '7.0'

env:
  global:
    - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost
#  matrix:
#    - WORDPRESS_VERSION=nightly
#    - WORDPRESS_VERSION=latest
#    - WORDPRESS_VERSION=4.8.5
#    - WORDPRESS_VERSION=4.7.9
#    - WORDPRESS_VERSION=4.6.10

# temp fix while chromedriver is broken on travis
# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
 chrome: stable

stages:
  - quality
  - test
    if: WORDPRESS_VERSION=nightly
  - behat

jobs:
  allow_failures:
    - env: STAGE=quality
  include:

    # PHPCS ###################################
    - stage: quality
      php: 7.1
      env:
        - WORDPRESS_VERSION=latest
        - STAGE=quality
      script: vendor/bin/phpcs

    # PHPUnit #################################
    - stage: test
      env:
        - WORDPRESS_VERSION=latest
        - STAGE=test
      script: vendor/bin/phpunit

    # Behat ###################################
    - stage: behat
      env:
        - STAGE=behat
      script: ./bin/behat.sh

cache:
  yarn: true
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install

after_script:
  # Tidy up after test run.
  # See https://github.com/travis-ci/travis-ci/issues/6861
  - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'java' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'Xvfb' | awk '{print $2}')
