language: php
php:
  - '7.2'
  - '7.1'
  - '7.0'
  - nightly

env:
  global:
    - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost

# temp fix while chromedriver is broken on travis
# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
 chrome: stable

stages:
  - quality
  - test
  - behat

jobs:
  allow_failures:
    - env: STAGE=quality
    - php: nightly
  include:
    # PHPCS #####################################
    - stage: quality
      env: STAGE=quality
      php: '7.1'
      script: vendor/bin/phpcs

    # PHPUnit ###################################
    - stage: test
      script: vendor/bin/phpunit

    # Behat #####################################
    - stage: behat
      env: WORDPRESS_VERSION=nightly
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=latest
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=latest
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=latest
      php: '7.1'
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=latest
      php: '7.0'
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=4.8.5
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=4.7.9
      script: ./bin/behat.sh

    - stage: behat
      env: WORDPRESS_VERSION=4.6.10
      script: ./bin/behat.sh

cache:
  yarn: true
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install

after_script:
  # Tidy up after test run.
  # See https://github.com/travis-ci/travis-ci/issues/6861
  - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'java' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'Xvfb' | awk '{print $2}')