language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:

  # Disable xDebug.
  - phpenv config-rm xdebug.ini || true

  # Update Composer.
  - composer self-update

install:
  - composer install
  # Install WordPress and start webserver.
  - bin/install-wp.sh
  - php -S "$WORDPRESS_URL" -t "$WORDPRESS_DIR" >/dev/null 2>&1 &
  # copy the plugin in the WordPress plugin folder
  - cp -r $TRAVIS_BUILD_DIR $WORDPRESS_DIR/wp-content/plugins/google-tag-manager
  # show the plugins folder contents to make sure the plugin folder is there
  - ls $WORDPRESS_DIR/wp-content/plugins

script:
  - vendor/bin/phpunit
  - vendor/bin/codecept run acceptance --env travis
